project_id = "jaxiekqndscqnrdtmxli"

[functions.send-password-reset]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.verify-reset-token]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false